### ISSUE TITLE
Do entity names in annotations have to be declared?

### ISSUE THREAD

**Issue by matentzn** [owlcs/argo#1]
Example given an otherwise empty ontology:
AnnotationAssertion(:A,hasSynonym,:B)
Should A and be have to be declared to pass the profile check?

**Comment by alanruttenberg** [comment]
No. It is explicit in the spec that the source of an annotation and the target, if a URI, are only URIs, not entities. 

AnnotationSubject := IRI | AnonymousIndividual
AnnotationValue := AnonymousIndividual | IRI | Literal

**Comment by matentzn** [comment]
Yep you are totally right, and that was not an issue. I thought it was, but I was mistaken. Closed.
